name: Waka Readme

on:
  schedule:
    # Runs at 12am EST
    - cron: '0 4 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_PROFILE_VIEWS: False
          SHOW_OS: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_LOC_CHART: False
          IGNORED_REPOS: "Function-Dev-Team/fob"
